development:
  adapter: postgresql
  encoding: unicode
  database: geo_pictures_development
  pool: 5  
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: geo_pictures_test
  pool: 5  
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: geo_pictures_production
  pool: 5  
  password:
